version: '3'

services:
  local_reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.8
    # Enables the web UI and tells Traefik to listen to docker
    container_name: local_reverse_proxy
    command: 
      - --api.insecure=true 
      - --api.dashboard=true
      - --api.debug=true
      - --providers.docker
      - --entrypoints.web.address=:80
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      #
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - local-web
      - local-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.service=api@internal"

  local_database:
    image: 'mcs07/postgres-rdkit'
    container_name: local_database
    shm_size: '4gb'
    environment:
      POSTGRES_SERVER: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWD: "$postgresPWD"
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - "kraken-postgres:/var/lib/postgresql/data"
      - "pr3:/home/db"
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -d postgres -c 'SELECT molecule_id FROM molecule LIMIT 1;' || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 5
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: postgres
    networks:
      - local-db

  local_backend:
    image: 'phosphines-backend:latest'
    container_name: local_backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    volumes:
      - "./backend/app:/app"
    environment:
      POSTGRES_SERVER: local_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWD: testing-password
      POSTGRES_DB: postgres
    entrypoint: bash prestart.sh
    depends_on:
      local_database:
        condition: service_healthy
    networks:
      - local-web
      - local-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"

  local_cdk-depict:
    image: 'simolecule/cdkdepict:latest'
    container_name: local_cdk-depcit
    networks:
      - local-web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cdk-depict.rule=Host(`localhost`) && PathPrefix(`/depict`)"

  local_frontend:
    image: 'phosphines-frontend:latest'
    container_name: local_frontend
    volumes:
      - "./frontend/src:/app/src"
      - "./frontend/public/stats:/app/public/stats"
    build:
      context: .
      dockerfile: frontend.development.dockerfile
    networks:
      - local-web
    entrypoint: npm start
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

  local_documentation:
    image: "phosphines-docs:latest"
    container_name: local_documentation
    build:
      context: ./docs
      dockerfile: docs.dockerfile
    entrypoint: bash start.sh
    volumes:
      - "./docs:/docs"
    networks:
      - local-web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.documentation.rule=Host(`localhost`) && PathPrefix(`/docs`)"
      - "traefik.http.services.documentation.loadbalancer.server.port=5000"
    

networks:
  local-web:
  local-db:

volumes:
  kraken-postgres:
      external: true
  pr3:
      external: true

