version: '3'

services:
  reverse-proxy:
    image: traefik:v2.9
    container_name: reverse_proxy
    command:
      - --api.insecure=false
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80

      # Uncomment below for SSL
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --certificatesresolvers.le.acme.email=janash@vt.edu
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --certificatesResolvers.le.acme.storage=/acme/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme:/acme
    networks:
      - web
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.service=api@internal"


  database:
    image: 'mcs07/postgres-rdkit'
    container_name: database
    shm_size: '4gb'
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "kraken-postgres:/var/lib/postgresql/data"
      - "pr3:/home/db"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: postgres
    networks:
      - db

  backend:
    image: 'phosphines-backend:latest'
    container_name: backend
    depends_on:
      - database
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    volumes:
      - "./backend/app:/app"
    environment:
      POSTGRES_SERVER: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWD: $postgresPWD
      POSTGRES_DB: postgres
    entrypoint: bash prestart.sh
    networks:
      - web
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`kraken.molssi.org`) && PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=le"

  cdk-depict:
    image: 'simolecule/cdkdepict:latest'
    container_name: cdk_depict
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cdk-depict.rule=Host(`kraken.molssi.org`) && PathPrefix(`/depict`)"
      - "traefik.http.routers.cdk-depict.tls=true"
      - "traefik.http.routers.cdk-depict.tls.certresolver=le"

  frontend:
    image: 'phosphines-frontend:latest'
    container_name: frontend
    volumes:
      - "./frontend/src:/app/src"
      - "./frontend/public/stats:/app/public/stats"
    build:
      context: .
      dockerfile: frontend.production.dockerfile
    networks:
      - web
    entrypoint: npm run serve
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`kraken.molssi.org`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=le"

  documentation:
    image: "phosphines-docs:latest"
    container_name: documentation
    build:
      context: ./docs
      dockerfile: docs.dockerfile
    entrypoint: bash start.sh
    volumes:
      - "./docs:/docs"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.documentation.rule=Host(`kraken.molssi.org`) && PathPrefix(`/docs`)"
      - "traefik.http.services.documentation.loadbalancer.server.port=5000"
      - "traefik.http.routers.documentation.tls=true"
      - "traefik.http.routers.documentation.tls.certresolver=le"    

networks:
  web:
  db:

volumes:
  kraken-postgres:
      external: true
  pr3:
      external: true
