version: "3.3"
services:
  
  database:
    image: 'mcs07/postgres-rdkit'
    container_name: database
    shm_size: '4gb'
    ports:
      - "5432:5432"
    volumes:
      - "kraken-postgres:/var/lib/postgresql/data"
      - "pr3:/home/db"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: postgres


  backend:
    image: 'phosphines-backend:latest'
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "80:8080"
    environment:
      POSTGRES_SERVER: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWD: 'password'
      POSTGRES_DB: postgres
    entrypoint: bash prestart.sh
      
  cdk-depict:
    image: 'simolecule/cdkdepict:1.3'
    ports:
      - "8081:8080"

volumes:
  kraken-postgres:
      external: true
  pr3:
      external: true
