name: base
channels:
  - conda-forge
dependencies:
  - python
  - rdkit
  - fastapi
  - pydantic-settings
  - alembic 
  - psycopg2-binary 
  - sqlalchemy 
  - pandas
  - tenacity 
  - uvicorn 
  - requests
  - curl 
  - openbabel