const dft_descriptors = {
  efg_amp_P: {
    descr: "Electric field gradient interaction amplitude",
    type: "Electronic",
    group: "EFG",
    unit: "atomic units",
  },
  efgtens_xx_P: {
    descr: "Electric field gradient interaction tensor XX component",
    type: "Electronic",
    group: "EFG",
    unit: "atomic units",
  },
  efgtens_yy_P: {
    descr: "Electric field gradient interaction tensor YY component",
    type: "Electronic",
    group: "EFG",
    unit: "atomic units",
  },
  efgtens_zz_P: {
    descr: "Electric field gradient interaction tensor ZZ component",
    type: "Electronic",
    group: "EFG",
    unit: "atomic units",
  },
  nuesp_P: {
    descr: "Nuclear electrostatic potential",
    type: "Electronic",
    group: "EFG",
    unit: "atomic units",
  },
  fmo_mu: {
    descr: "chemical potential / molecular electronegativity",
    type: "Electronic",
    group: "Frontier orbital derived",
    unit: "Hartree",
  },
  fmo_omega: {
    descr: "Global electrophilicity parameter ω",
    type: "Electronic",
    group: "Frontier orbital derived",
    unit: "Hartree",
  },
  fmo_e_homo: {
    descr: "HOMO energy",
    type: "Electronic",
    group: "Frontier orbital derived",
    unit: "Hartree",
  },
  fmo_eta: {
    descr: "HOMO-LUMO gap, molecular softness",
    type: "Electronic",
    group: "Frontier orbital derived",
    unit: "Hartree",
  },
  fmo_e_lumo: {
    descr: "LUMO energy",
    type: "Electronic",
    group: "Frontier orbital derived",
    unit: "Hartree",
  },
  fukui_m: {
    descr: "Atom-condensed Fukui index f–",
    type: "Electronic",
    group: "Fukui",
    unit: "",
  },
  fukui_p: {
    descr: "Atom-condensed Fukui index f+",
    type: "Electronic",
    group: "Fukui",
    unit: "",
  },
  nmr_P: {
    descr: "magnetic shielding constant of P",
    type: "Electronic",
    group: "NMR",
    unit: "ppm",
  },
  nmrtens_sxx_P: {
    descr: "magnetic shielding tensor XX component",
    type: "Electronic",
    group: "NMR",
    unit: "ppm",
  },
  nmrtens_syy_P: {
    descr: "magnetic shielding tensor YY component",
    type: "Electronic",
    group: "NMR",
    unit: "ppm",
  },
  nmrtens_szz_P: {
    descr: "magnetic shielding tensor ZZ component",
    type: "Electronic",
    group: "NMR",
    unit: "ppm",
  },
  nbo_bds_e_avg: {
    descr: "average P–X antibonding orbital energy",
    type: "Electronic",
    group: "Orbitals",
    unit: "Hartree",
  },
  nbo_bds_occ_avg: {
    descr: "average P–X antibonding orbital occupancy",
    type: "Electronic",
    group: "Orbitals",
    unit: "",
  },
  nbo_bd_e_avg: {
    descr: "average P–X bonding orbital energy",
    type: "Electronic",
    group: "Orbitals",
    unit: "Hartree",
  },
  nbo_bd_occ_avg: {
    descr: "average P–X bonding orbital occupancy",
    type: "Electronic",
    group: "Orbitals",
    unit: "",
  },
  nbo_bds_occ_max: {
    descr: "highest P–X antibonding orbital occupancy",
    type: "Electronic",
    group: "Orbitals",
    unit: "",
  },
  nbo_bd_e_max: {
    descr: "highest P–X bonding orbital energy",
    type: "Electronic",
    group: "Orbitals",
    unit: "Hartree",
  },
  nbo_bds_e_min: {
    descr: "lowest P–X antibonding orbital energy",
    type: "Electronic",
    group: "Orbitals",
    unit: "Hartree",
  },
  nbo_bd_occ_min: {
    descr: "lowest P–X bonding orbital occupancy",
    type: "Electronic",
    group: "Orbitals",
    unit: "",
  },
  nbo_P: {
    descr: "Natural population (ground state)",
    type: "Electronic",
    group: "NBO",
    unit: "",
  },
  nbo_lp_P_e: {
    descr: "P lone pair orbital energy",
    type: "Electronic",
    group: "Orbitals",
    unit: "Hartree",
  },
  nbo_lp_P_occ: {
    descr: "P lone pair orbital occupancy",
    type: "Electronic",
    group: "Orbitals",
    unit: "",
  },
  nbo_lp_P_percent_s: {
    descr: "P lone pair orbital s-percentage",
    type: "Electronic",
    group: "Orbitals",
    unit: "%",
  },
  nbo_P_ra: {
    descr: "Natural population (radical anion)",
    type: "Electronic",
    group: "Radical Anion",
    unit: "",
  },
  E_reduction: {
    descr: "Ionization potential/Reduction potential (vertical)",
    type: "Electronic",
    group: "Radical Anion",
    unit: "Hartree",
  },
  somo_ra: {
    descr: "SOMO energy in radical anion (single point)",
    type: "Electronic",
    group: "Radical Anion",
    unit: "Hartree",
  },
  spindens_P_ra: {
    descr: "Spin density at P in radical anion (single point)",
    type: "Electronic",
    group: "Radical Anion",
    unit: "",
  },
  nbo_P_rc: {
    descr: "Natural population (radical cation)",
    type: "Electronic",
    group: "Radical Cation",
    unit: "",
  },
  E_oxidation: {
    descr: "Electron affinity/Oxidation potential (vertical)",
    type: "Electronic",
    group: "Radical Cation",
    unit: "Hartree",
  },
  somo_rc: {
    descr: "SOMO energy in radical cation (single point)",
    type: "Electronic",
    group: "Radical Cation",
    unit: "Hartree",
  },
  spindens_P_rc: {
    descr: "Spin density at P in radical cation (single point)",
    type: "Electronic",
    group: "Radical Cation",
    unit: "",
  },
  vmin_r: {
    descr: "distance of Vmin from P",
    type: "Electronic",
    group: "Vmin",
    unit: "Å",
  },
  vmin_vmin: {
    descr:
      "Vmin / minimum of molecular electrostatic potential in P lone pair region",
    type: "Electronic",
    group: "Vmin",
    unit: "",
  },
  dipolemoment: {
    descr: "Dipole moment",
    type: "Full molecule / Interaction",
    group: "Dipole",
    unit: "Debye",
  },
  Pint_P_max: {
    descr: "Maximum of dispersion parameter P on the molecule",
    type: "Full molecule / Interaction",
    group: "Pint",
    unit: "kcal0.5 mol−0.5",
  },
  Pint_P_min: {
    descr: "Minimum of dispersion parameter P on the molecule",
    type: "Full molecule / Interaction",
    group: "Pint",
    unit: "kcal0.5 mol−0.5",
  },
  Pint_P_int: {
    descr: "Molecular dispersion descriptor Pint",
    type: "Full molecule / Interaction",
    group: "Pint",
    unit: "kcal0.5 mol−0.5",
  },
  Pint_dP: {
    descr: "Standard deviation of dispersion parameter P",
    type: "Full molecule / Interaction",
    group: "Pint",
    unit: "kcal0.5 mol−0.5",
  },
  qpole_amp: {
    descr: "Quadrupole moment amplitude",
    type: "Full molecule / Interaction",
    group: "Quadrupole",
    unit: "Debye-Ang",
  },
  qpoletens_xx: {
    descr: "Quadrupole moment tensor XX component",
    type: "Full molecule / Interaction",
    group: "Quadrupole",
    unit: "Debye-Ang",
  },
  qpoletens_yy: {
    descr: "Quadrupole moment tensor YY component",
    type: "Full molecule / Interaction",
    group: "Quadrupole",
    unit: "Debye-Ang",
  },
  qpoletens_zz: {
    descr: "Quadrupole moment tensor ZZ component",
    type: "Full molecule / Interaction",
    group: "Quadrupole",
    unit: "Debye-Ang",
  },
  E_solv_elstat: {
    descr: "Electrostatic component of energy of solvation",
    type: "Full molecule / Interaction",
    group: "Solvation",
    unit: "kcal/mol",
  },
  E_solv_total: {
    descr: "Energy of solvation",
    type: "Full molecule / Interaction",
    group: "Solvation",
    unit: "kcal/mol",
  },
  E_solv_cds: {
    descr: "Non-electrostatic component of energy of solvation",
    type: "Full molecule / Interaction",
    group: "Solvation",
    unit: "kcal/mol",
  },
  sphericity: {
    descr: "Sphericity ",
    type: "Steric",
    group: "Dimensions",
    unit: "",
  },
  surface_area: {
    descr: "Surface area",
    type: "Steric",
    group: "Dimensions",
    unit: "Å2",
  },
  volume: { descr: "Volume", type: "Steric", group: "Dimensions", unit: "Å3" },
  pyr_P: {
    descr: "Pyramidalization P",
    type: "Steric",
    group: "Pyramidalization",
    unit: "",
  },
  pyr_alpha: {
    descr: "Pyramidalization α angle",
    type: "Steric",
    group: "Pyramidalization",
    unit: "",
  },
  sterimol_burB1: {
    descr: "buried Sterimol B1",
    type: "Steric",
    group: "Sterimol",
    unit: "Å",
  },
  sterimol_burB5: {
    descr: "buried Sterimol B5",
    type: "Steric",
    group: "Sterimol",
    unit: "Å",
  },
  sterimol_burL: {
    descr: "buried Sterimol L",
    type: "Steric",
    group: "Sterimol",
    unit: "Å",
  },
  sterimol_B1: {
    descr: "Sterimol B1 value",
    type: "Steric",
    group: "Sterimol",
    unit: "Å",
  },
  sterimol_B5: {
    descr: "Sterimol B5 value",
    type: "Steric",
    group: "Sterimol",
    unit: "Å",
  },
  sterimol_L: {
    descr: "Sterimol L value",
    type: "Steric",
    group: "Sterimol",
    unit: "Å",
  },
  vbur_vbur: {
    descr: "Buried volume",
    type: "Steric",
    group: "Vbur",
    unit: "Å3",
  },
  vbur_max_delta_qvbur: {
    descr: "Highest buried volume difference between two neighboring quadrants",
    type: "Steric",
    group: "Vbur",
    unit: "Å3",
  },
  vbur_ovbur_max: {
    descr: "Highest octant buried volume",
    type: "Steric",
    group: "Vbur",
    unit: "Å3",
  },
  vbur_ovtot_max: {
    descr: "Highest octant total volume",
    type: "Steric",
    group: "Vbur",
    unit: "Å3",
  },
  vbur_qvbur_max: {
    descr: "Highest quadrant buried volume",
    type: "Steric",
    group: "Vbur",
    unit: "Å3",
  },
  vbur_qvtot_max: {
    descr: "Highest quadrant total volume",
    type: "Steric",
    group: "Vbur",
    unit: "Å3",
  },
  vbur_max_delta_qvtot: {
    descr: "Highest total volume difference between two neighboring quadrants",
    type: "Steric",
    group: "Vbur",
    unit: "Å3",
  },
  vbur_ovbur_min: {
    descr: "Lowest octant buried volume",
    type: "Steric",
    group: "Vbur",
    unit: "Å3",
  },
  vbur_ovtot_min: {
    descr: "Lowest octant total volume",
    type: "Steric",
    group: "Vbur",
    unit: "Å3",
  },
  vbur_qvbur_min: {
    descr: "Lowest quadrant buried volume",
    type: "Steric",
    group: "Vbur",
    unit: "Å3",
  },
  vbur_qvtot_min: {
    descr: "Lowest quadrant total volume",
    type: "Steric",
    group: "Vbur",
    unit: "Å3",
  },
  vbur_vtot: {
    descr: "Molecular vdW volume from buried volume calculation",
    type: "Steric",
    group: "Vbur",
    unit: "Å3",
  },
  vbur_ratio_vbur_vtot: {
    descr: "Ratio of buried to total volume",
    type: "Steric",
    group: "Vbur",
    unit: "",
  },
  vbur_near_vbur: {
    descr: "z- Hemisphere buried volume",
    type: "Steric",
    group: "Vbur",
    unit: "Å3",
  },
  vbur_near_vtot: {
    descr: "z- Hemisphere total volume",
    type: "Steric",
    group: "Vbur",
    unit: "Å3",
  },
  vbur_far_vbur: {
    descr: "z+ Hemisphere buried volume",
    type: "Steric",
    group: "Vbur",
    unit: "Å3",
  },
  vbur_far_vtot: {
    descr: "z+ Hemisphere total volume",
    type: "Steric",
    group: "Vbur",
    unit: "Å3",
  },
};

export default dft_descriptors;
