const xtb_descriptors = {
  global_electrophilicity_index: {
    unit: "eV",
    descr: " ",
    type: "Electronic",
    group: "Frontier orbital derived",
  },
  nucleophilicity: {
    unit: "eV",
    descr: "Global nucleophilicity N",
    type: "Electronic",
    group: "Frontier orbital derived",
  },
  HOMO_LUMO_gap: {
    unit: "eV",
    descr: "HOMO-LUMO gap",
    type: " molecular softness",
    group: "Electronic,Frontier orbital derived",
  },
  IP_delta_SCC: {
    unit: "eV",
    descr: "Ionization potential/Reduction potential (vertical)",
    type: "Electronic",
    group: "Radical Anion",
  },
  EA_delta_SCC: {
    unit: "eV",
    descr: "Electron affinity/Oxidation potential (vertical)",
    type: "Electronic",
    group: "Radical Cation",
  },
  dip: {
    unit: "Debye",
    descr: "Dipole moment",
    type: "Full molecule / Interaction",
    group: "Dipole",
  },
  dip_norm: {
    unit: "Debye",
    descr: "Normalized dipole moment",
    type: "Full molecule / Interaction",
    group: "Dipole",
  },
  p_int_atom_area: {
    unit: "Å2",
    descr: "Atom area in the Pint calculation",
    type: "Full molecule / Interaction",
    group: "Pint",
  },
  p_int: {
    unit: "kcal0.5 mol−0.5",
    descr: "Molecular dispersion descriptor Pint",
    type: "Full molecule / Interaction",
    group: "Pint",
  },
  p_int_area: {
    unit: "Å2",
    descr: "Molecule surface area in the Pint calculation",
    type: "Full molecule / Interaction",
    group: "Pint",
  },
  p_int_atom: {
    unit: "kcal0.5 mol−0.5",
    descr: "Pint of the P atom",
    type: "Full molecule / Interaction",
    group: "Pint",
  },
  p_int_atom_times_p_int_atom_area: {
    unit: "kcal0.5 mol−0.5 Å2",
    descr: "Pint of the P atom times its area",
    type: "Full molecule / Interaction",
    group: "Pint",
  },
  p_int_times_p_int_area: {
    unit: "kcal0.5 mol−0.5 Å2",
    descr: "Pint times the area of the molecule",
    type: "Full molecule / Interaction",
    group: "Pint",
  },
  alpha: {
    unit: "a.u.",
    descr: "Molecular polarizability",
    type: "Full molecule / Interaction",
    group: "Polarizability",
  },
  cone_angle: {
    unit: "degrees",
    descr: "Exact ligand cone angle",
    type: "Steric",
    group: "Cone angle",
  },
  pyr_val: {
    unit: "",
    descr: "Pyramidalization P",
    type: "Steric",
    group: "Pyramidalization",
  },
  pyr_alpha: {
    unit: "degrees",
    descr: "Pyramidalization α angle",
    type: "Steric",
    group: "Pyramidalization",
  },
  sasa: {
    unit: "Å2",
    descr: "Molecular solvent accessible surface area",
    type: "Steric",
    group: "SASA",
  },
  sasa_volume_P: {
    unit: "",
    descr: "P atom solvent accessible surface area",
    type: "Steric",
    group: "SASA",
  },
  sasa_P: {
    unit: "Å2",
    descr: "Solvent accessible surface area of the P atom",
    type: "Steric",
    group: "SASA",
  },
  sasa_volume: {
    unit: "Å3",
    descr: "Volume enclosed by the molecular solvent accessible surface",
    type: "Steric",
    group: "SASA",
  },
  B1: {
    unit: "Å",
    descr: "Sterimol B1 value",
    type: "Steric",
    group: "Sterimol",
  },
  B5: {
    unit: "Å",
    descr: "Sterimol B5 value",
    type: "Steric",
    group: "Sterimol",
  },
  lval: {
    unit: "Å",
    descr: "Sterimol L value",
    type: "Steric",
    group: "Sterimol",
  },
  vbur: { unit: "Å3", descr: "Buried volume", type: "Steric", group: "Vbur" },
  max_delta_qvbur: {
    unit: "Å3",
    descr: "Highest buried volume difference between two neighboring quadrants",
    type: "Steric",
    group: "Vbur",
  },
  ovbur_max: {
    unit: "Å3",
    descr: "Highest octant buried volume",
    type: "Steric",
    group: "Vbur",
  },
  ovtot_max: {
    unit: "Å3",
    descr: "Highest octant total volume",
    type: "Steric",
    group: "Vbur",
  },
  qvbur_max: {
    unit: "Å3",
    descr: "Highest quadrant buried volume",
    type: "Steric",
    group: "Vbur",
  },
  qvtot_max: {
    unit: "Å3",
    descr: "Highest quadrant total volume",
    type: "Steric",
    group: "Vbur",
  },
  max_delta_qvtot: {
    unit: "Å3",
    descr: "Highest total volume difference between two neighboring quadrants",
    type: "Steric",
    group: "Vbur",
  },
  ovbur_min: {
    unit: "Å3",
    descr: "Lowest octant buried volume",
    type: "Steric",
    group: "Vbur",
  },
  ovtot_min: {
    unit: "Å3",
    descr: "Lowest octant total volume",
    type: "Steric",
    group: "Vbur",
  },
  qvbur_min: {
    unit: "Å3",
    descr: "Lowest quadrant buried volume",
    type: "Steric",
    group: "Vbur",
  },
  qvtot_min: {
    unit: "Å3",
    descr: "Lowest quadrant total volume",
    type: "Steric",
    group: "Vbur",
  },
  vtot: {
    unit: "Å3",
    descr: "Molecular vdW volume from buried volume calculation",
    type: "Steric",
    group: "Vbur",
  },
  near_vbur: {
    unit: "Å3",
    descr: "z- Hemisphere buried volume",
    type: "Steric",
    group: "Vbur",
  },
  near_vtot: {
    unit: "Å3",
    descr: "z- Hemisphere total volume",
    type: "Steric",
    group: "Vbur",
  },
  far_vbur: {
    unit: "Å3",
    descr: "z+ Hemisphere buried volume",
    type: "Steric",
    group: "Vbur",
  },
  far_vtot: {
    unit: "Å3",
    descr: "z+ Hemisphere total volume",
    type: "Steric",
    group: "Vbur",
  },
};
export default xtb_descriptors;
